### PR TITLE
Heather guesses controller

### PR DESCRIPTION
**Pull request by jeder28**
Yeay after the first guess is made on a deck, a new round is created, by using the user id.

If there is no user id logged in and stored in session a guest_id is created and entered into session to create the round!

### CODE REVIEW

**Comment by jkrth617** [comment]
@jeder28 the logic looks great. good job with the creating a guest so we dont have to force someone into making an account. Since we create a round every time in the guessing logic maybe we need either some control flow that checks if we have some round id in the session or maybe we need to create the round before the first guess and then after creating a new round it redirects to the first card show page and the user can start answering cards? :snowman: :+1:  :cactus: :cake: 

edit- like you said after the first guess a round is created. maybe the round should be created and then that should lead to the guessing (we could store round_id in the session or get it from the user_id and finding that users last round created). That way after a round is created the logic just loops over itself showing cards and creating guesses till all the cards are done.

**Comment by jeder28** [comment]
@jkrth617, I like the idea of creating the round before the first card is shown. What I'm wondering now is how the round would end. Could the round end if you decided you didn't want to finish the game and return to the  all decks or user page?

**Comment by jkrth617** [comment]
@jeder28 They way the challenge has it laid out is the user has to answer all the cards. In our controller where we subtract the spent cards from the list of every card in the deck we could have a control flow statement that checks to see if the remain array is empty (ie all the questions have been answered correctly and by subtracting them from the deck.cards array we have nothing left). If we have an empty array we could route to the round show page which shows the statistics and then saves it and does that logic instead of looping to another card. If we want to give the user an option to give up we could also implement that in addition to completing the deck. 

thats atleast how I thought about it, I havent checked the code today

**Comment by jeder28** [comment]
@jkrth617 @kimchanyoung @lksevans12 
So I moved making a new guest user and round in the deck controller, and now it eventually runs out of cards to choose! I get a nil error when no more are left! how exciting :)  I'll try to fix the flow so it goes to the stats page once you run out of valid cards and then push up the new branch. :dancer: :dango:  :dart:

**Comment by jeder28** [comment]
Please close this pull request!

**Pull request closed without merging**
